name: Continuous Integration

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/ci.yaml'
            - 'config/**'
            - 'src/**'
            - 'templates/**'
            - 'tests/**'
            - 'composer.json'
            - 'phpcs.xml.dist'
            - 'phpstan.dist.neon'
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.1', '8.2', '8.3']
                symfony-version: ['6.*', '7.*']
                dependency-version: [highest]
#                include:
#                    - php-version: '8.1'
#                      symfony-version: 6.*
#                      dependency-version: lowest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Install packages
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependency-version }}

            - name: Install PHPUnit
              run: vendor/bin/simple-phpunit install

            - name: Run PHPCS
              run: vendor/bin/phpcs

            - name: Run PHPStan
              run: vendor/bin/phpstan analyze

            - name: Run tests
              run: vendor/bin/simple-phpunit
